name: Build LaTeX document
on:
  push:
    branches:
      - master
      - development
      - release
  pull_request:
    branches:
      - master
      - development
      - release
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: article.tex

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: draft.pdf
          path: article.pdf
        
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: article.pdf
          tag_name: auto_build_draft
          name: Auto build draft
